[package]
name = "starboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twilight-gateway = "0.14.1"
twilight-http = "0.14.2"
twilight-model = "0.14.3"
twilight-validate = "0.14.2"
twilight-util = { version = "0.14.2", features = ["builder", "snowflake"] }
twilight-interactions = "0.14.4"
twilight-mention = "0.14.0"
twilight-standby = "0.14.1"

async-trait = "0.1.63"
tokio = { version = "1.25.0", features = ["full"] }
futures = "0.3.21"
dotenv = "0.15.0"
sqlx = { version = "0.6.0", features = ["macros", "postgres", "offline", "runtime-tokio-rustls", "chrono", "json"]}
chrono = "0.4.19"
serde_json = "1.0"
serde = "1.0.139"
emojis = "0.5.1"
dashmap = "5.3.4"
regex = "1.6.0"
lazy_static = "1.4.0"
humantime = "2.1.0"
reqwest = "0.11.14"
sentry = "0.29.2"
floodgate = "0.5.0"
thousands = "0.2.0"
snafu = { version = "0.7.4", features = ["backtraces-impl-backtrace-crate"] }
serde_with = "2.2.0"
psutil = "3.2.2"
rust-fuzzy-search = "0.1.1"
moka = { version = "0.9.6", features = ["future"] }
