[package]
name = "starboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twilight-gateway = "0.11.0"
twilight-http = "0.11.0"
twilight-cache-inmemory = "0.11.0"
twilight-model = "0.11.0"
twilight-util = { version = "0.11.0", features = ["builder"] }

twilight-interactions = "0.11.0"

async-trait = "0.1.56"
tokio = { version = "1.19.2", features = ["full"] }
futures = "0.3.21"
dotenv = "0.15.0"
anyhow = "1.0.58"
