# this compose file is mostly for dev; you will likely not use it as-is for production
# deployment

name: starboard

services:
  postgres:
    image: docker.io/postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    command: >
      postgres
      -c shared_buffers=1GB
      -c work_mem=4MB
      -c max_connections=25
    volumes:
      - ./.postgres/postgres18:/var/lib/postgresql:Z

  starboard:
    build:
      context: .
      dockerfile: Containerfile
    env_file: .env
    environment:
      SB_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    restart: unless-stopped
    depends_on: [postgres]
