version: "3.8"
services:
  db:
    image: postgres:15.3
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  backup:
    image: ${IMAGE_BACKUP}
    restart: always
    env_file: .env
    build:
      dockerfile: services/backup/Dockerfile
    depends_on:
      - db
    volumes:
      - backup:/backups

  proxy:
    image: ghcr.io/germanoeich/nirn-proxy:v1.3.2
    restart: always
    env_file: .env
    ports:
       - "8080:8080"

  website:
    image: ${IMAGE_WEBSITE}
    restart: always
    env_file: .env
    build:
      dockerfile: services/website/Dockerfile
    ports:
      - "8000:8000"

  bot:
    image: ${IMAGE_BOT}
    restart: always
    env_file: .env
    build:
      dockerfile: services/bot/Dockerfile
    depends_on:
      - db
      - proxy

volumes:
  db:
    driver: local
  backup:
    driver: local
