version: "3.8"
services:
  db:
    image: postgres:15.3
    restart: always
    network_mode: bridge
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  proxy:
    image: ghcr.io/germanoeich/nirn-proxy:v1.3.2
    restart: always
    network_mode: bridge
    env_file: .env
    ports:
       - "8080:8080"

  bot:
    image: circuitsacul/starboard-compose:latest
    restart: always
    env_file: .env
    network_mode: bridge
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
      - proxy
    links:
      - db
      - proxy

volumes:
  db:
    driver: local
