[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = { version = "5.5.0", optional = true }
dotenv = { version = "0.15.0", optional = true }

[features]
backend = ["dep:dotenv", "dep:dashmap"]
