name: test

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Test
        run: echo "TAG_NAME=$(git describe --tags)" >> $GITHUB_ENV
